Добавление декоративных картинок
htmlacademy-htmlcss/2370985-sedona-37 pull request #6
Opened 2023-06-30 16:24 UTC by barnicl1490

2023-07-10 16:43 UTC, Kartaviy-arteom requested changes

2023-07-10 16:43 UTC, Kartaviy-arteom commented on .vscode/launch.json
> +            "name": "Open index.html",
зачем это в репозитории?

2023-07-10 16:43 UTC, Kartaviy-arteom commented on index.html
> +                  required>
label

2023-07-10 16:43 UTC, Kartaviy-arteom commented on index.html
> +                </button>
кнопкам скрытое описание

2023-07-14 13:28 UTC, merged

2023-07-18 16:09 UTC, Julia-Julia-Julia1 commented
Артем! Я увидела что могу писать ответ! Это здорово!